# Generated by Django 4.2.2 on 2023-07-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('packSize', 'packSize')], max_length=100),
        ),
    ]
